const a = {
    Quarter: 4,
    SecLeft: 5,
    players: [
        {
            name: 'K. Love',
            role: 'PF',
            type: 'starter',
            on: true,
            team: 'CLE',
            FG: '5 - 16',
            '3PT': '0 - 5',
            FT: '0 - 0',
            OREB: 3,
            DREB: 15,
            REB: 18,
            AST: 4,
            STL: 0,
            BLK: 2,
            TO: 1,
            PF: 2,
            time: 0,
            PTS: 10
        },
        {
            name: 'L. James',
            role: 'SF',
            type: 'starter',
            on: true,
            team: 'CLE',
            FG: '10 - 26',
            '3PT': '1 - 5',
            FT: '4 - 9',
            OREB: 2,
            DREB: 7,
            REB: 9,
            AST: 2,
            STL: 1,
            BLK: 2,
            TO: 4,
            PF: 0,
            time: 0,
            PTS: 25
        },
        {
            name: 'T. Mozgov',
            role: 'C',
            type: 'starter',
            on: false,
            team: 'CLE',
            FG: '0 - 5',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 3,
            DREB: 0,
            REB: 3,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 1,
            PF: 3,
            time: 0,
            PTS: 0
        },
        {
            name: 'K. Irving',
            role: 'PG',
            type: 'starter',
            on: false,
            team: 'CLE',
            FG: '4 - 15',
            '3PT': '0 - 6',
            FT: '5 - 5',
            OREB: 3,
            DREB: 0,
            REB: 3,
            AST: 2,
            STL: 1,
            BLK: 0,
            TO: 2,
            PF: 1,
            time: 0,
            PTS: 13
        },
        {
            name: 'J. Smith',
            role: 'G',
            type: 'starter',
            on: true,
            team: 'CLE',
            FG: '4 - 9',
            '3PT': '4 - 8',
            FT: '2 - 3',
            OREB: 0,
            DREB: 1,
            REB: 1,
            AST: 0,
            STL: 1,
            BLK: 0,
            TO: 2,
            PF: 3,
            time: 0,
            PTS: 14
        },
        {
            name: 'T. Thompson',
            role: 'C',
            type: 'bench',
            on: true,
            team: 'CLE',
            FG: '3 - 6',
            '3PT': '0 - 0',
            FT: '2 - 2',
            OREB: 3,
            DREB: 7,
            REB: 10,
            AST: 1,
            STL: 1,
            BLK: 0,
            TO: 0,
            PF: 5,
            time: 0,
            PTS: 8
        },
        {
            name: 'M. Williams',
            role: 'PG',
            type: 'bench',
            on: true,
            team: 'CLE',
            FG: '0 - 1',
            '3PT': '0 - 0',
            FT: '3 - 3',
            OREB: 0,
            DREB: 0,
            REB: 0,
            AST: 1,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 3
        },
        {
            name: 'M. Dellavedova',
            role: 'PG',
            type: 'bench',
            on: true,
            team: 'CLE',
            FG: '4 - 11',
            '3PT': '0 - 3',
            FT: '2 - 3',
            OREB: 2,
            DREB: 3,
            REB: 5,
            AST: 1,
            STL: 1,
            BLK: 0,
            TO: 1,
            PF: 4,
            time: 0,
            PTS: 10
        },
        {
            name: 'J. Jones',
            role: 'SG',
            type: 'bench',
            on: true,
            team: 'CLE',
            FG: '0 - 0',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 2,
            REB: 2,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 0
        },
        {
            name: 'I. Shumpert',
            role: 'G',
            type: 'bench',
            on: false,
            team: 'CLE',
            FG: '0 - 6',
            '3PT': '0 - 3',
            FT: '0 - 0',
            OREB: 1,
            DREB: 3,
            REB: 4,
            AST: 1,
            STL: 1,
            BLK: 0,
            TO: 0,
            PF: 4,
            time: 0,
            PTS: 0
        },
        {
            name: 'R. Jefferson',
            role: 'F',
            type: 'bench',
            on: false,
            team: 'CLE',
            FG: '0 - 0',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 0
        },
        {
            name: 'A. Varejao',
            role: 'C',
            type: 'bench',
            on: false,
            team: 'CLE',
            FG: '0 - 0',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 0
        },
        {
            name: 'J. Cunningham',
            role: 'G',
            type: 'bench',
            on: false,
            team: 'CLE',
            FG: '0 - 0',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 0
        },
        {
            name: 'D. Green',
            role: 'PF',
            type: 'starter',
            on: true,
            team: 'GSW',
            FG: '8 - 17',
            '3PT': '2 - 3',
            FT: '4 - 7',
            OREB: 1,
            DREB: 14,
            REB: 15,
            AST: 7,
            STL: 0,
            BLK: 2,
            TO: 4,
            PF: 2,
            time: 0,
            PTS: 22
        },
        {
            name: 'B. Rush',
            role: 'F',
            type: 'starter',
            on: false,
            team: 'GSW',
            FG: '0 - 5',
            '3PT': '0 - 2',
            FT: '0 - 0',
            OREB: 0,
            DREB: 3,
            REB: 3,
            AST: 0,
            STL: 1,
            BLK: 0,
            TO: 1,
            PF: 1,
            time: 0,
            PTS: 0
        },
        {
            name: 'A. Bogut',
            role: 'C',
            type: 'starter',
            on: false,
            team: 'GSW',
            FG: '2 - 2',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 3,
            DREB: 4,
            REB: 7,
            AST: 1,
            STL: 0,
            BLK: 4,
            TO: 0,
            PF: 2,
            time: 0,
            PTS: 4
        },
        {
            name: 'S. Curry',
            role: 'PG',
            type: 'starter',
            on: true,
            team: 'GSW',
            FG: '6 - 15',
            '3PT': '1 - 4',
            FT: '6 - 6',
            OREB: 1,
            DREB: 6,
            REB: 7,
            AST: 7,
            STL: 2,
            BLK: 0,
            TO: 3,
            PF: 3,
            time: 0,
            PTS: 19
        },
        {
            name: 'K. Thompson',
            role: 'SG',
            type: 'starter',
            on: true,
            team: 'GSW',
            FG: '6 - 16',
            '3PT': '1 - 4',
            FT: '5 - 6',
            OREB: 2,
            DREB: 4,
            REB: 6,
            AST: 1,
            STL: 0,
            BLK: 1,
            TO: 1,
            PF: 1,
            time: 0,
            PTS: 18
        },
        {
            name: 'A. Iguodala',
            role: 'F',
            type: 'bench',
            on: true,
            team: 'GSW',
            FG: '1 - 6',
            '3PT': '1 - 5',
            FT: '4 - 6',
            OREB: 0,
            DREB: 2,
            REB: 2,
            AST: 3,
            STL: 1,
            BLK: 1,
            TO: 0,
            PF: 1,
            time: 0,
            PTS: 7
        },
        {
            name: 'M. Speights',
            role: 'F',
            type: 'bench',
            on: false,
            team: 'GSW',
            FG: '0 - 1',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 0,
            REB: 0,
            AST: 0,
            STL: 1,
            BLK: 0,
            TO: 1,
            PF: 2,
            time: 0,
            PTS: 0
        },
        {
            name: 'J. McAdoo',
            role: 'SF',
            type: 'bench',
            on: false,
            team: 'GSW',
            FG: '0 - 0',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 1,
            REB: 1,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 0
        },
        {
            name: 'F. Ezeli',
            role: 'C',
            type: 'bench',
            on: false,
            team: 'GSW',
            FG: '1 - 4',
            '3PT': '0 - 0',
            FT: '1 - 2',
            OREB: 0,
            DREB: 4,
            REB: 4,
            AST: 0,
            STL: 0,
            BLK: 2,
            TO: 2,
            PF: 1,
            time: 0,
            PTS: 3
        },
        {
            name: 'L. Barbosa',
            role: 'G',
            type: 'bench',
            on: false,
            team: 'GSW',
            FG: '0 - 2',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 1,
            REB: 1,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 2,
            time: 0,
            PTS: 0
        },
        {
            name: 'S. Livingston',
            role: 'G',
            type: 'bench',
            on: true,
            team: 'GSW',
            FG: '8 - 9',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 1,
            DREB: 2,
            REB: 3,
            AST: 2,
            STL: 1,
            BLK: 0,
            TO: 4,
            PF: 5,
            time: 0,
            PTS: 16
        },
        {
            name: 'I. Clark',
            role: 'G',
            type: 'bench',
            on: false,
            team: 'GSW',
            FG: '0 - 1',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 0,
            REB: 0,
            AST: 0,
            STL: 1,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 0
        },
        {
            name: 'J. Thompson',
            role: 'PF',
            type: 'bench',
            on: false,
            team: 'GSW',
            FG: '0 - 0',
            '3PT': '0 - 0',
            FT: '0 - 0',
            OREB: 0,
            DREB: 0,
            REB: 0,
            AST: 0,
            STL: 0,
            BLK: 0,
            TO: 0,
            PF: 0,
            time: 0,
            PTS: 0
        }
    ]
}